In [53]:
pip install seaborn

Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/prashanth/Library/Python/3.11/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/prashanth/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as ply
import seaborn as sns

In [55]:
df=pd.read_csv("air_quality_no2.csv")
df.head()

              datetime  station_antwerp  station_paris  station_london
0  2019-05-07 02:00:00              NaN            NaN            23.0
1  2019-05-07 03:00:00             50.5           25.0            19.0
2  2019-05-07 04:00:00             45.0           27.7            19.0
3  2019-05-07 05:00:00              NaN           50.4            16.0
4  2019-05-07 06:00:00              NaN           61.9             NaN

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   datetime         1035 non-null   object
 1   station_antwerp  95 non-null     float64
 2   station_paris    1004 non-null   float64
 3   station_london   969 non-null    float64
dtypes: float64(3), object(1)
memory usage: 32.5+ KB

In [57]:
df.dtypes

datetime            object
station_antwerp    float64
station_paris      float64
station_london     float64
dtype: object

In [58]:
df.describe()

       station_antwerp  station_paris  station_london
count        95.000000    1004.000000      969.000000
mean         25.778947      27.740538       24.777090
std          12.682019      15.285746       11.214377
min           7.500000       0.000000        0.000000
25%          16.750000      16.500000       19.000000
50%          23.000000      24.150000       25.000000
75%          34.500000      35.925000       31.000000
max          74.500000      97.000000       97.000000

In [59]:
df.isnull().sum()*100/len(df)

datetime            0.000000
station_antwerp    90.821256
station_paris       2.995169
station_london      6.376812
dtype: float64

In [60]:
# 1. drop antwarp
# 2. Starts with paris dataset
# 3. datime should be sorte

In [61]:
df.drop(columns='station_antwerp',inplace=True)

In [62]:
(df['station_paris']==0).sum()

np.int64(7)

In [63]:
df.columns

Index(['datetime', 'station_paris', 'station_london'], dtype='object')

In [64]:
df['datetime']=pd.to_datetime(df['datetime'])

In [65]:
df.dtypes

datetime          datetime64[ns]
station_paris            float64
station_london           float64
dtype: object

In [66]:
df.head()

             datetime  station_paris  station_london
0 2019-05-07 02:00:00            NaN            23.0
1 2019-05-07 03:00:00           25.0            19.0
2 2019-05-07 04:00:00           27.7            19.0
3 2019-05-07 05:00:00           50.4            16.0
4 2019-05-07 06:00:00           61.9             NaN

In [67]:
df=df.set_index('datetime')
df.head()

                     station_paris  station_london
datetime
2019-05-07 02:00:00            NaN            23.0
2019-05-07 03:00:00           25.0            19.0
2019-05-07 04:00:00           27.7            19.0
2019-05-07 05:00:00           50.4            16.0
2019-05-07 06:00:00           61.9             NaN

In [68]:
df['station_paris'].isnull().sum()

np.int64(31)

In [69]:
df=df.sort_index()
df.head()

                     station_paris  station_london
datetime
2019-05-07 02:00:00            NaN            23.0
2019-05-07 03:00:00           25.0            19.0
2019-05-07 04:00:00           27.7            19.0
2019-05-07 05:00:00           50.4            16.0
2019-05-07 06:00:00           61.9             NaN

In [70]:
df.isnull().sum()

station_paris     31
station_london    66
dtype: int64

In [71]:
(df['station_paris']==0).sum()

np.int64(7)

In [72]:
df.dtypes

station_paris     float64
station_london    float64
dtype: object

In [73]:
df2=df.copy()
df2.dtypes

station_paris     float64
station_london    float64
dtype: object

In [74]:
df['station_paris'] = df['station_paris'].replace(0,np.nan)
df.dtypes

station_paris     float64
station_london    float64
dtype: object

In [75]:
(df['station_paris']==0).sum()

np.int64(0)

In [76]:
df['station_paris'].isnull().sum()

np.int64(38)

In [77]:
df['paris_lag1']=df['station_paris'].shift(1)
df.head(10)

                     station_paris  station_london  paris_lag1
datetime
2019-05-07 02:00:00            NaN            23.0         NaN
2019-05-07 03:00:00           25.0            19.0         NaN
2019-05-07 04:00:00           27.7            19.0        25.0
2019-05-07 05:00:00           50.4            16.0        27.7
2019-05-07 06:00:00           61.9             NaN        50.4
2019-05-07 07:00:00           72.4            26.0        61.9
2019-05-07 08:00:00           77.7            32.0        72.4
2019-05-07 09:00:00           67.9            32.0        77.7
2019-05-07 10:00:00           56.0            28.0        67.9
2019-05-07 11:00:00           34.5            21.0        56.0

In [78]:
df.isnull().sum()

station_paris     38
station_london    66
paris_lag1        39
dtype: int64

In [79]:
df.drop(columns='station_london',inplace=True)

In [80]:
df['station_paris']=df['station_paris'].ffill()
df['station_paris'] = df['station_paris'].bfill()
df.isnull().sum()

station_paris     0
paris_lag1       39
dtype: int64

In [81]:
df['paris_lag1']=df['paris_lag1'].ffill()
df['paris_lag1'] = df['paris_lag1'].bfill()
df.isnull().sum()

station_paris    0
paris_lag1       0
dtype: int64

In [82]:
df.head()

                     station_paris  paris_lag1
datetime
2019-05-07 02:00:00           25.0        25.0
2019-05-07 03:00:00           25.0        25.0
2019-05-07 04:00:00           27.7        25.0
2019-05-07 05:00:00           50.4        27.7
2019-05-07 06:00:00           61.9        50.4

In [83]:
df['hour'] = df.index.hour
df['month'] = df.index.month
df['weekday'] = df.index.weekday

In [84]:
df['paris_lag2'] = df['paris_lag1'].shift(1)
df.head()

,station_paris,paris_lag1,hour,month,weekday,paris_lag2
datetime,,,,,,
2019-05-07 02:00:00,25.0,25.0,2,5,1,NaN
2019-05-07 03:00:00,25.0,25.0,3,5,1,25.0
2019-05-07 04:00:00,27.7,25.0,4,5,1,25.0
2019-05-07 05:00:00,50.4,27.7,5,5,1,25.0
2019-05-07 06:00:00,61.9,50.4,6,5,1,27.7

In [85]:
df=df.dropna()
df.isnull().sum()

station_paris    0
paris_lag1       0
hour             0
month            0
weekday          0
paris_lag2       0
dtype: int64

In [86]:
df.head()

,station_paris,paris_lag1,hour,month,weekday,paris_lag2
datetime,,,,,,
2019-05-07 03:00:00,25.0,25.0,3,5,1,25.0
2019-05-07 04:00:00,27.7,25.0,4,5,1,25.0
2019-05-07 05:00:00,50.4,27.7,5,5,1,25.0
2019-05-07 06:00:00,61.9,50.4,6,5,1,27.7
2019-05-07 07:00:00,72.4,61.9,7,5,1,50.4

In [87]:
# Here We have predict the station_paris NO2 at a time 't'
# for this purpose 'X' is input and 'Y' is output 
# Here Y --> output --> station_paris
# Here X --> inputs --> paris_lag1,paris_lag2,hour,month,weekday

In [88]:
y=df['station_paris']
X=df.drop(columns='station_paris')
X.head()

                     paris_lag1  hour  month  weekday  paris_lag2
datetime
2019-05-07 03:00:00        25.0     3      5        1        25.0
2019-05-07 04:00:00        25.0     4      5        1        25.0
2019-05-07 05:00:00        27.7     5      5        1        25.0
2019-05-07 06:00:00        50.4     6      5        1        27.7
2019-05-07 07:00:00        61.9     7      5        1        50.4

In [89]:
y.head()

datetime
2019-05-07 03:00:00    25.0
2019-05-07 04:00:00    27.7
2019-05-07 05:00:00    50.4
2019-05-07 06:00:00    61.9
2019-05-07 07:00:00    72.4
Name: station_paris, dtype: float64

In [90]:
print(type(0.8*len(df)))
train_size=int(0.8*len(df))
print(type(int(0.8*len(df))))
train_size

<class 'float'>
<class 'int'>

827

In [91]:
y_train=y.iloc[:train_size]
y_test=y.iloc[train_size:]
print(len(y_train))
print(len(y_test))

827
207

In [92]:
X_train=X.iloc[:train_size]
X_test=X.iloc[train_size:]
print(len(X_train))
print(len(X_test))

827
207

### LinearRegression Model

In [93]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [94]:
y_pred=model.predict(X_test)

In [95]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 5.075237058717491
RMSE: 7.2864392702310985
R2: 0.8050506212611871

### RandomForestRegression Model

In [96]:
from sklearn.ensemble import RandomForestRegressor

rf_model=RandomForestRegressor(n_estimators=50,
                      random_state=42)
rf_model.fit(X_train,y_train)

RandomForestRegressor(n_estimators=50, random_state=42)

In [97]:
y_pred_train = rf_model.predict(X_train)
y_pred_test = rf_model.predict(X_test)

In [98]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("Train MAE:", mean_absolute_error(y_train, y_pred_train))
print("Train RMSE:", np.sqrt(mean_squared_error(y_train, y_pred_train)))
print("Train R2:", r2_score(y_train, y_pred_train))

Train MAE: 1.977813784764208
Train RMSE: 3.0343986166839536
Train R2: 0.957986793019755

In [99]:
print("Test MAE:", mean_absolute_error(y_test, y_pred_test))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_test)))
print("Test R2:", r2_score(y_test, y_pred_test))

Test MAE: 4.964521739130434
Test RMSE: 7.4212500372876535
Test R2: 0.7977701384105997

### GradientBoostingRegressor

In [101]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

gbr=GradientBoostingRegressor(n_estimators=100,
                          learning_rate=0.2,
                          max_depth=3,
                          random_state=42)

gbr.fit(X_train,y_train)

GradientBoostingRegressor(learning_rate=0.2, random_state=42)

In [102]:
# Predictions
y_pred_train=gbr.predict(X_train)
y_pred_test=gbr.predict(X_test)

In [103]:
# Training Performance
print(f"Train MAE : {mean_absolute_error(y_train,y_pred_train)}")
print(f"Train RMSE : {np.sqrt(mean_squared_error(y_train,y_pred_train))}")
print(f"Train R2 : {r2_score(y_train,y_pred_train)}")

Train MAE : 3.0263268925108897
Train RMSE : 4.151620675255484
Train R2 : 0.9213541333765252

In [104]:
# Test performance
print("Test MAE:", mean_absolute_error(y_test, y_pred_test))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_test)))
print("Test R2:", r2_score(y_test, y_pred_test))

Test MAE: 4.970544803621769
Test RMSE: 7.469916844197196
Test R2: 0.7951090902193666