In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [8]:
df=pd.read_csv("diabetes.csv")

In [9]:
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [10]:
df.shape

(768, 9)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [12]:
X = df.drop(columns=['Outcome'])
X

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [13]:
y = df['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)
X_train

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
353            1       90             62  ...  27.2                     0.580   24
711            5      126             78  ...  29.6                     0.439   40
373            2      105             58  ...  34.9                     0.225   25
46             1      146             56  ...  29.7                     0.564   29
682            0       95             64  ...  44.6                     0.366   22
..           ...      ...            ...  ...   ...                       ...  ...
451            2      134             70  ...  28.9                     0.542   23
113            4       76             62  ...  34.0                     0.391   25
556            1       97             70  ...  38.1                     0.218   30
667           10      111             70  ...  27.5                     0.141   40
107            4      144             58  ...  29.5                     0.287   37

[614 rows x 8 columns]

In [15]:
#Euclidean_distance
classifier = KNeighborsClassifier(p=2)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
acc = accuracy_score (y_test, y_pred)
print ("Accuracy:",acc)

Accuracy: 0.6688311688311688

In [18]:
#manhattan_distance
classifier = KNeighborsClassifier(p=1)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

[1 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0
 0 1 0 0 0 0 0 0 1 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 1 1 0
 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1
 1 0 0 0 1 0]
0.7272727272727273

In [26]:
X_test

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
44             7      159             64  ...  27.4                     0.294   40
672           10       68            106  ...  35.5                     0.285   47
700            2      122             76  ...  35.9                     0.483   26
630            7      114             64  ...  27.4                     0.732   34
81             2       74              0  ...   0.0                     0.102   22
..           ...      ...            ...  ...   ...                       ...  ...
32             3       88             58  ...  24.8                     0.267   22
637            2       94             76  ...  31.6                     0.649   23
593            2       82             52  ...  28.5                     1.699   25
425            4      184             78  ...  37.0                     0.264   31
273            1       71             78  ...  33.2                     0.422   21

[154 rows x 8 columns]

In [27]:
y_test

44     0
672    0
700    0
630    1
81     0
      ..
32     0
637    0
593    0
425    1
273    0
Name: Outcome, Length: 154, dtype: int64

In [31]:

c=[[7,159,64,0,0,27.4,0.294,40]]
g=classifier.predict(c)
accuracy = accuracy_score([0], g)
accuracy

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

0.0